service: serverless-five9-scim
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  catchAll:
    timeout: 60
    memorySize: 128
    handler: api/app.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin