service: serverless-five9-scim
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  user:
    timeout: 30
    memorySize: 128
    handler: api/app.handler
    events:
      - httpApi:
          path: 'scimv2/Users/{id}'
          method: 'ANY'

  users:
    timeout: 30
    memorySize: 128
    handler: api/app.handler
    events:
      - httpApi: 
          path: 'scimv2/Users'
          method: 'ANY'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin