service: serverless-five9-scim
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ usersTable, Arn ]
  environment:
    USERS_TABLE: USERS

resources:
      Resources:
        usersTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: USERS
            AttributeDefinitions:
              - AttributeName: id
                AttributeType: N
            KeySchema:              
              - AttributeName: id
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

functions:
  user:
    timeout: 30
    memorySize: 128
    handler: api/app.handler
    events:
      - httpApi:
          path: '/scimv2/Users/{id}'
          method: 'ANY'

  users:
    timeout: 30
    memorySize: 128
    handler: api/app.handler
    events:
      - httpApi: 
          path: '/scimv2/Users'
          method: 'ANY'

  sync:
    handler: api/sync.handler
    events:
      - schedule:
          rate: rate(1 day)

plugins:
  - serverless-offline
  - serverless-dotenv-plugin